sudo: required
services:
  - docker

before_install:
  - docker build -t yoooonghyun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yoooonghyun/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-251619182877"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
